my_virtual_assitant/my_virtual_assitant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("chat/", include('poetic_assitant.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='chat/', permanent=True)),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

my_virtual_assitant/poetic_assitant/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index.as_view(), name='index'),
]

my_virtual_assitant/poetic_assitant/models.py
from django.db import models

# Create your models here.

my_virtual_assitant/poetic_assitant/forms.py
from django import forms

class Prompts_Form(forms.Form):
    user_entery = forms.CharField(max_length=50, 
                        widget=forms.TextInput(attrs={
                            'class': 'w3-button w3-border  w3-round-xlarge',
                            'placeholder': 'Introduz o nome do topíco...'
                        }))

my_virtual_assitant/poetic_assitant/views.py
import os
from django.shortcuts import render, redirect
from django.views import View
from poetic_assitant.forms import Prompts_Form

from openai import OpenAI



class index(View):
    openai_api_key = ENTER_YOUR_API_KEY
    client = OpenAI(api_key=openai_api_key)

    def get(self, request, *args, **kwargs):
        return render(request, 'index.html', {
            'form': Prompts_Form(),
        })

    def post(self, request, *args, **kwargs):
        openai_api_key = ENTER_YOUR_API_KEY
        client = OpenAI(api_key=openai_api_key)

        num_visits = request.session.get('num_visits', 3)
        request.session['num_visits'] = num_visits + 1
        
        if num_visits > 5:
                response = 'Your number of questions time up' 
                
        else:
            form = Prompts_Form(data=request.POST)
            if form.is_valid():
                prompt = form.cleaned_data['user_entery']
                
                try:
                    completion = client.chat.completions.create(model="gpt-3.5-turbo",messages=[
                            {"role": "system", "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."},
                            {"role": "user", "content": 'Crie um poema com o seguinte tópico em programação e sua logíca' + prompt}
                        ],
                    temperature=0,
                    max_tokens=1024)
                    response = completion.choices[0].message.content

                except Exception as e:
                    response = "Erro durante a solicitação da API"

                
        return render(request, 'index.html', {
                'response': response, 
                'form' : Prompts_Form(),
                'num_visits': num_visits})

my_virtual_assitant/poetic_assitant/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/w3.css' %}">
    <style>
        input#id_user_entery {
                width: 21em;
                padding: 1em;   
        }
        input.w3-indigo.w3-round-xlarge.w3-border.w3-button{
            padding: 1em;
        }

    </style>
</head>
<body>
    <main class="w3-mobile">
        
        <h1 class="w3-center w3-padding w3-padding-16 w3-jumbo "></h1>
        <section class="w3-margin-top">
            <div class="w3-margin-top w3-padding-24">
                <p class="w3-center "  style="max-width: 63%; margin: 0 auto;">
                    <img src="{% static 'icones/brilliance.svg' %}" style="width: 17em;"  alt="Icon de balance">
                </p>
            </div>
        </section>
        <section class="w3-center w3-animate-zoom">
            <form action="." method="post">
                {% csrf_token %}
                <p>
                    {{ form.user_entery }}
        
                <input type="submit" class="w3-indigo w3-round-xlarge w3-border w3-button"  value="Enviar">
                </p>
            </form>
        
            <div class="w3-margin-top w3-justify" >
                <p class="w3-animate-zoom w3-large w3-padding-16" style="max-width: 63%; margin: 0 auto;"">
                    <i> - {{ response }}</i> <br>
                </p>
                <center><small>O Programa pode esta lento.. </small></center>
                <center><small>Número total de pergunga: 3</small></center>
                <center><small>Em homenagem à: Dionisía Madureira</small></center>
            </div>
        
        </section>
    </main>
</body>
</html>